name: test-workflow
on:
  push:
    branches:
      - main
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Tagging Testing
        run: echo "Test tagging!"
      - name: Tagging Entity
        run: |
          curl https://api.newrelic.com/graphql \
          -H 'Content-Type: application/json' \
          -H 'API-Key: ${{ secrets.NEW_RELIC_API_KEY }}' \
          --data-binary '{"query":"mutation {\n  taggingAddTagsToEntity(\n    guid: \"MzYyNzU0MXxJTkZSQXxOQXwzMzk4MTU5MDE3MjkyMzM1MjA0\"\n    tags: {key: \"My_Pet\", values: \"Dogs\"}\n  ) {\n    errors {\n      message\n      type\n    }\n  }\n}", "variables":""}'
