name: test-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Testing code
        run: echo "Hello world!"
      - name: Testing code 2
        run: echo "testing code"
